name: CI

on:
  push:
    branches: [ main ]
    tags:
      - "*"
  pull_request:
  schedule:
  - cron:  '0 0 * * *'
  workflow_dispatch:

jobs:

  vendor:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Vendor
      run: |
        make vendor
        git diff --exit-code

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Setup yarn
      run: npm install -g yarn
    - name: Build
      run: make

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Setup yarn
      run: npm install -g yarn
    - name: Build kg and kgctl for all Linux Architectures
      run: make all-build

  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Run Unit Tests
      run: make unit

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19
    - name: Lint Code
      run: make lint
